# Version of the configuration file
version: 3.0.0
# Icarus theme variant, can be "default" or "cyberpunk"
variant: default
# Path or URL to the website's logo
logo: 
    light: /img/logo.png
    dark: /img/logo.png
# Page metadata configurations
head:
    # URL or path to the website's icon
    favicon: /img/favicon.ico
    # Open Graph metadata
    # https://hexo.io/docs/helpers.html#open-graph
    open_graph:
        # Page title (og:title) (optional)
        # You should leave this blank for most of the time
        title: LollipopKit Blog
        # Page type (og:type) (optional)
        # You should leave this blank for most of the time
        type: blog
        # Page URL (og:url) (optional)
        # You should leave this blank for most of the time
        url: https://lollipopkit.com
        # Page cover (og:image) (optional)
        # You should leave this blank for most of the time
        image: /img/favicon.ico
        # Site name (og:site_name) (optional)
        # You should leave this blank for most of the time
        site_name: Lolli Blog
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author: LollipopKit
        # Page description (og:description) (optional)
        # You should leave this blank for most of the time
        description: java,python,web,android，技术分享
        # Twitter card type (twitter:card)
        twitter_card: 
        # Twitter ID (twitter:creator)
        twitter_id: 
        # Twitter Site (twitter:site)
        twitter_site: 
        # Google+ profile link (deprecated)
        google_plus: 
        # Facebook admin ID
        fb_admins: 
        # Facebook App ID
        fb_app_id: 
    # Structured data of the page
    # https://developers.google.com/search/docs/guides/intro-structured-data
    structured_data:
        # Page title (optional)
        # You should leave this blank for most of the time
        title: Lolli Blog
        # Page description (optional)
        # You should leave this blank for most of the time
        description: java,python,web,android,技术分享
        # Page URL (optional)
        # You should leave this blank for most of the time
        url: https://lollipopkit.com
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author: LollipopKit
        # Page images (optional)
        # You should leave this blank for most of the time
        image: /img/favicon.ico
    # Additional HTML meta tags in an array
    meta:
        # Meta tag specified in <attribute>=<value> style
        # E.g., name=theme-color;content=#123456 => <meta name="theme-color" content="#123456">
        - ''
    # URL or path to the website's RSS atom.xml
    rss: 
# Page top navigation bar configurations
navbar:
    # Naviagtion menu items
    menu:
        主页: /
        归档: /archives
        分类: /categories
        标签: /tags
        关于: /about
    # Links to be shown on the right of the navigation bar
    links:
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/LollipopKit'
# Page footer configurations
footer:
    # Links to be shown on the right of the footer section
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: 'https://creativecommons.org/'
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: 'https://creativecommons.org/licenses/by/4.0/'
        Download on GitHub:
            icon: fab fa-github
            url: 'https://github.com/LollipopKit'
# Article related configurations
article:
    # Code highlight settings
    highlight:
        # Code highlight themes
        # https://github.com/highlightjs/highlight.js/tree/master/src/styles
        theme: atom-one-light
        # Show copy code button
        clipboard: true
        # Default folding status of the code blocks. Can be "", "folded", "unfolded"
        fold: unfolded
    # Whether to show thumbnail image for every article
    thumbnail: true
    # Whether to show estimated article reading time
    readtime: true
# Search plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search/
search:
    type: insight
# Comment plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment/
comment:
    type: disqusjs
    # Disqus shortname
    shortname: lolli-blog
    api_key: 81kBQnlivtAbGKND6Hgpw1MKCFvcyJ07ZdzC7MDicuVfZd2uilFVvBKHvCfAX6sX
# Donate plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Donation/
donates:
    # Alipay donate button configurations
    -
        type: alipay
        # Alipay qrcode image URL
        qrcode: '/img/IMG_1652.JPG'    
    # Wechat donate button configurations
    -
        type: wechat
        # Wechat qrcode image URL
        qrcode: '/img/IMG_1653.JPG'
# Share plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share/
share:
    type: sharethis
    # URL to the ShareThis share plugin script
    install_url: 'https://platform-api.sharethis.com/js/sharethis.js#property=5ecfbfe49590190013f0f4dd&product=inline-share-buttons'
# Sidebar configurations.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
    # Left sidebar configurations
    left:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: true
    # Right sidebar configurations
    right:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: true
# Sidebar widget configurations
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    # Table of contents widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: toc
    # Profile widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: profile
        # Author name
        author: LollipopKit
        # Author title
        author_title: a pythonista
        # Author's current location
        location: Chengdu, Sichuan, China
        # URL or path to the avatar image
        avatar: /img/favicon.ico
        # Whether show the rounded avatar image
        avatar_rounded: true
        # Email address for the Gravatar
        gravatar: 
        # URL or path for the follow button
        follow_link: 'https://github.com/LollipopKit'
        # Links to be shown on the bottom of the profile widget
        social_links:
            Github:
                icon: fab fa-instagram
                url: 'https://www.instagram.com/lollipop.kit/'
            Weibo:
                icon: fab fa-weibo
                url: 'https://weibo.com/u/2807936220'
            Email:
                icon: fa fa-envelope
                url: 'mailto:2036293523@qq.com'
            #Facebook:
                #icon: fab fa-facebook
                #url: 'https://facebook.com'
            #Twitter:
                #icon: fab fa-twitter
                #url: 'https://twitter.com'
            QQ:
                icon: fab fa-qq
                url: 'https://qm.qq.com/cgi-bin/qm/qr?k=br1IidFeIyetsv39kO-fc0c9Bkn7Mkkt&noverify=0'
            #RSS:
                #icon: fas fa-rss
                #url: /


    # Recommendation links widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: links
        # Names and URLs of the sites
        links:
            Lolli Tool: 'https://fjy.pub'
            Rayfantasy: 'https://rayfantasy.com'
            Mashiro APT: 'https://repo.mashiro.cloud'
            
    # Categories widget configurations
    #-
        # Where should the widget be placed, left sidebar or right sidebar
        #position: left
        #type: categories
    # Recent posts widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: recent_posts
    # Archives widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: archives
    # Tags widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: right
        type: tags
    # Google FeedBurner email subscription widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: subscribe_email
        # Hint text under the email input
        description: 
        # Feedburner ID
        feedburner_id: ''
    # Google AdSense unit configurations
    #-
        # Where should the widget be placed, left sidebar or right sidebar
        #position: left
        #type: adsense
        # AdSense client ID
        #client_id: 'ca-pub-9459720830319889'
        # AdSense AD unit ID
        #slot_id: '123456'
# Plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/
plugins:
    # Enable page startup animations
    animejs: true
    # Show the "back to top" button
    back_to_top: true
    # Baidu Analytics plugin settings
    # https://tongji.baidu.com
    #baidu_analytics:
        # Baidu Analytics tracking ID
        #tracking_id: 
    # BuSuanZi site/page view counter
    # https://busuanzi.ibruce.info
    busuanzi: true
    # CNZZ statistics
    # https://www.umeng.com/web
    #cnzz:
        # CNZZ tracker id
        #id: 
        # CNZZ website id
        #web_id: 
    # Enable the lightGallery and Justified Gallery plugins
    gallery: true
    # Google Analytics plugin settings
    # https://analytics.google.com
    google_analytics:
        # Google Analytics tracking ID
        tracking_id:  UA-103581318-2
    # Hotjar user feedback plugin
    # https://www.hotjar.com/
    #hotjar:
        # Hotjar site id
        #site_id: 
    # Enable the KaTeX math typesetting supprot
    # https://katex.org/
    katex: false
    # Enable the MathJax math typesetting support
    # https://www.mathjax.org/
    mathjax: false
    # Enable the Outdated Browser plugin
    # http://outdatedbrowser.com/
    outdated_browser: false
    # Show a progress bar at top of the page on page loading
    progressbar: false
# CDN provider settings
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
    # Name or URL template of the JavaScript and/or stylesheet CDN provider
    cdn: jsdelivr
    # Name or URL template of the webfont CDN provider
    fontcdn: google
    # Name or URL of the fontawesome icon font CDN provider
    iconcdn: fontawesome
